name: Scheduled Build and Deploy

on:
  schedule:
    - cron: '20 16 * * * Asia/Kolkata'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Install actions/timezone action
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        run: |
          npm install actions/timezone

      - name: Set timezone
        uses: actions/timezone@v3
        with:
          timezone: Asia/Kolkata

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          cd /home/icanio-10091/Music/Linux-santhosh
          git stash && git pull
          pm2 ls
          pm2 delete react
          pm2 start npm --name react -- start
