name: Schedule Trigger

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Running
        run: |
          date
          ls
          pwd

          json_payload='{
            "cards": [
              {
                "header": {
                  "title": "Titandata Database Backup Completed",
                  "imageUrl": "https://cdn.theorg.com/f7155400-1112-4398-9e8d-44a1f056b3b9_medium.jpg",
                  "imageStyle": "AVATAR"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "textParagraph": {
                          "text": "<b>Database:</b> '\"$DB_NAME\"'"
                        }
                      },
                      {
                        "textParagraph": {
                          "text": "<b>Enviroment:</b> 'QA'"
                        }
                      },
                      {
                        "textParagraph": {
                          "text": "<b>S3 Bucket:</b> '\"$S3_BUCKET/$S3_FOLDER\"'"
                        }
                      },
                      {
                        "textParagraph": {
                          "text": "<b>File Name:</b> '\"$BACKUP_FILENAME\"'"
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }'

          # Send JSON payload using cURL to Google Chat
          echo "$json_payload" | curl -s --request POST \
            --header "Content-Type: application/json" \
            --data @- \
            "https://chat.googleapis.com/v1/spaces/AAAAiYRfdXo/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=g_0nbpFNOz5S45a_KClz6Mpq-VkR6baR54pD5FNgwrQ"






# name: Build and Deploy

# on:
#   workflow_run:
#     workflows: ["Scheduled Trigger"]
#     types:
#       - completed
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: self-hosted
#     steps:
#       # - name: Install timezonectl package
#       #   run: |
#       #     npm install timezonectl@latest --registry https://npm.pkg.github.com/

#       - name: Set timezone
#         run: |
#           echo "TZ=UTC" >> ~/.bashrc
#           source ~/.bashrc

#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Install dependencies
#         run: |
#           npm install

#       - name: Build
#         run: |
#           npm run build

#   deploy:
#     runs-on: self-hosted
#     #if: github.event_name == 'workflow_run' && github.event.workflow == 'Scheduled Trigger'
#     needs: build
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Deploy
#         run: |
#           cd /home/icanio-10091/Music/Linux-santhosh
#           git stash && git pull
#           pm2 ls
#           pm2 delete react
#           pm2 start npm --name react -- start


# name: Master Build and Deploy

# on:
#   push:
#     branches:
#       - main
#   schedule:
#     - cron: '5 4 * * *'

# jobs:
#   build:
#     runs-on: self-hosted
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#   deploy:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Deploy
#         run: |
#           cd /home/icanio-10091/Music/Linux-santhosh
#           git stash
#           git pull
#           pm2 ls
#           # Check if the workflow was triggered by a push event
#           if [ "${{ github.event_name }}" == "push" ]; then
#             # pm2 delete react
#             pm2 start npm --name react -- start
#           else
#             echo "Not a push event. Skipping deletion and restart of the application."
#           fi

