name: Build and Deploy

on:
  push:
    branches:
      - main
  schedule:
      - cron: '25 13 * * *'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: react
        run: |
          cd /home/icanio-10091/Music/Linux-santhosh
          pm2 ls
          pm2 delete react
          #pm2 delete react
          pm2 start npm --name react -- start
          # Add commands to deploy your React app to the self-hosted environment
          # This could involve copying files, starting a server, etc.
