name: Scheduled Trigger

on:
  schedule:
    - cron: '41 5 * * 1,2,3,4,5,6'

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build Workflow
        uses: actions/github-script@0.12.0
        with:
          script: |
            const { data: workflow } = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file: 'main.yml', // Specify your main workflow file name
            });
            console.log(`Workflow ${workflow.id} triggered.`);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
