# name: Scheduled Trigger

# on:
#   schedule:
#     - cron: '41 5 * * 1,2,3,4,5,6'

# jobs:
#   trigger-build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Trigger Build Workflow
#         uses: actions/github-script@0.12.0
#         with:
#           script: |
#             const { data: workflow } = await github.actions.createWorkflowDispatch({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               workflow_file: 'main.yml', // Specify your main workflow file name
#             });
#             console.log(`Workflow ${workflow.id} triggered.`);
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Scheduled Trigger

on:
  schedule:
    - cron: '47 17 * * 1,2,3,4,5,6'

jobs:
  trigger-build:
    runs-on: self-hosted
    steps:
      - name: Set System Time
        run: |
          # Set the system time to '2023-11-14 17:47:03'
          sudo timedatectl set-time '2023-11-14 17:47:03'
          sudo hwclock --systohc  # Optional: Update hardware clock

      - name: Trigger Build Workflow
        uses: actions/github-script@0.12.0
        with:
          script: |
            const { data: workflow } = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file: 'main.yml', // Specify your main workflow file name
            });
            console.log(`Workflow ${workflow.id} triggered.`);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
